version: '3.8'

services:
  composer:
    image: composer:latest
    working_dir: /app
    volumes:
      - .:/app
    command: ["composer", "install"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vue_frontend
    ports:
      - "8080:8080"
    volumes:
      - .:/var/www/html

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: yii_api
    volumes:
      - .:/var/www/html
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
    ports:
      - "8081:80"
    depends_on:
      - composer
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yii_backend
    volumes:
      - .:/var/www/html
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
    ports:
      - "8002:80"
    depends_on:
      - composer
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d appdb"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
volumes:
  db-data:
